version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        SPRING_DB_DIALECT: ${SPRING_DB_DIALECT}
    ports:
      - "8080:8080"

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/e-mobility
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DB_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - db

  #client:
    #build: ../client
    #ports:
      #- "80:80"
    #depends_on:
      #- api

  db:
    image: postgres:14.7
    environment:
      - POSTGRES_DB=e-mobility
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql



volumes:
  postgres-data: {}
